### ISSUE TITLE
不支持到类型enum

### ISSUE THREAD

**Issue by bqf9979** [xxjwxc/gormt#10]
panic: type (enum('true','false')) not match in any way.

**Comment by bqf9979** [comment]
github.com/xxjwxc/gormt/data/view/gtools.OnGetTypeName(0xc00040e380, 0x14, 0x937704, 0x1)
	/Users/xxj/work/workspace/github/xxjwxc/gormt/data/view/gtools/common.go:219 +0x218
github.com/xxjwxc/gormt/data/view/gtools.OnGetTableElement(0xc000301cb0, 0xc000374110, 0x8, 0x7, 0x2, 0xc000297710)
	/Users/xxj/work/workspace/github/xxjwxc/gormt/data/view/gtools/common.go:120 +0x4cb
github.com/xxjwxc/gormt/data/view/gtools.OnGetPackageInfo(0xc000301cb0, 0xc000360180, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/xxj/work/workspace/github/xxjwxc/gormt/data/view/gtools/common.go:60 +0x1a4
github.com/xxjwxc/gormt/data/view/gtools.Execute()
	/Users/xxj/work/workspace/github/xxjwxc/gormt/data/view/gtools/gtools.go:24 +0xbf
github.com/xxjwxc/gormt/data/cmd.glob..func1(0xdfd900, 0xc0002171d0, 0x0, 0x5)
	/Users/xxj/work/workspace/github/xxjwxc/gormt/data/cmd/cmd.go:26 +0x20
github.com/spf13/cobra.(*Command).execute(0xdfd900, 0xc00009e130, 0x5, 0x5, 0xdfd900, 0xc00009e130)
	/Users/xxj/work/path/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xdfd900, 0x0, 0x0, 0x8460a8)
	/Users/xxj/work/path/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/xxj/work/path/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/xxjwxc/gormt/data/cmd.Execute()
	/Users/xxj/work/workspace/github/xxjwxc/gormt/data/cmd/cmd.go:34 +0x2e
main.main()
	/Users/xxj/work/workspace/github/xxjwxc/gormt/main.go:6 +0x20

**Comment by xxjwxc** [comment]
如果有不支持的类型：需要你添加到
https://github.com/xxjwxc/gormt/blob/master/data/view/cnf/def.go#11 （精确类型）
https://github.com/xxjwxc/gormt/blob/master/data/view/cnf/def.go#28 （模糊匹配类型）

欢迎pull request 中完善。

**Comment by bqf9979** [comment]
为什么生成的都是json 而不是demo里那种gorm,需要调整什么?
例如生成到如下结构体:
type CmChannel struct {
	ID     int    `gorm:"primary_key" json:"-"`
	Sn     string `json:"sn"`
	Tags   string `json:"tags"`   // 标签,逗号分隔
	Status int    `json:"status"` // 状态
	Name   string `json:"name"`   // 支付方式名称
	Remark string `json:"remark"` // 应用场景描述
}

**Comment by bqf9979** [comment]
抱歉,我找到了参数,并且生成了,还带了SQL的注释,如果能屏蔽就好了,另外建议不要强制用配置文件,单用指令生成挺方便

**Comment by xxjwxc** [comment]
您好：指令是有的。可能没有完全覆盖。我尽快写上去

**Comment by xxjwxc** [comment]
另外：建议使用简单模式，因为gorm标签对于当前生成的结构体是自动支持的，这样看起来代码更简洁。json标签没有屏蔽掉是因为json标签使用的是小驼峰标准（用于网络传输）。so ...

**Comment by xxjwxc** [comment]
Problem solved
