### ISSUE TITLE
数据库表,没有做过外键,有什么好的方案吗

### ISSUE THREAD

**Issue by huchenghua** [xxjwxc/gormt#101]
mdoels里又想关联起来的, 有什么好的方案吗

**Comment by xxjwxc** [comment]
可以通过配置文件来，还有注解(需要开发)

**Comment by huchenghua** [comment]
> 可以通过配置文件来，还有注解(需要开发)

加油,我先自己改哈

**Comment by xxjwxc** [comment]
https://github.com/xxjwxc/gormt/commit/689c8a30d9ba14bbe3df901e66bd9f0a1f05551f

已添加：注释前请加入[@fk tablename.columnname] 来配置自定义外键

**Comment by huchenghua** [comment]
> [689c8a3](https://github.com/xxjwxc/gormt/commit/689c8a30d9ba14bbe3df901e66bd9f0a1f05551f)
> 
> 已添加：注释前请加入[@fk tablename.columnname] 来配置自定义外键

mysql的字段注释里写吗比如有个字段是  uid 是不是,下面这样可以可以
```
用户的id[@fk users.uid]
```

**Comment by xxjwxc** [comment]
是的：但是注释必须以：[@fk users.uid] 开头。后边可以加注释。
regex定义是：
