### ISSUE TITLE
对于Json类型字段应增加datatypes.JSON的支持。

### ISSUE THREAD

**Issue by tnngo** [xxjwxc/gormt#102]
其datatypes.JSON类型位于gorm.io/datatypes库下。

**Comment by xxjwxc** [comment]
有具体文档地址吗?

**Comment by xxjwxc** [comment]
https://github.com/go-gorm/datatypes
找到了，我看下尽快支持下，请关注后继更新

**Comment by xxjwxc** [comment]
https://github.com/xxjwxc/gormt/commit/a0b28c40889701cbd59dba5e8c095589289844e7
已经添加

**Comment by tnngo** [comment]
Very good and good job.
