### ISSUE TITLE
表前缀匹配不生效

### ISSUE THREAD

**Issue by nanfangstation** [xxjwxc/gormt#105]
目标：支持单个表的代码生成
实际：GUI经常卡死，遂尝试cmd命令，看到代码应该支持表前缀模糊匹配的，但是各种尝试均不生效，'-t'，'--table_prefix'，求解，不想每次生成全量
`./gormt -g=false -H=xxx.xxx.xxx.xxx -d=xx -p=x -u=x --port=x --table_prefix=table_name -F=true -o=/Users/xxx/model `

**Comment by xxjwxc** [comment]
你是编译的新版本还是用release下载的？
如果是下载的，版本比较老还没更新上去的

**Comment by nanfangstation** [comment]
之前拉的是编译后的可以直接运行 后来拉源码改了调试发现这个table_prefix功能只是为了替换变量名 每次跑还是会跑全量数据 最终我自己改源码实现了

发自我的iPhone

**Comment by xxjwxc** [comment]
如果实现有问题可以提PR

**Comment by nanfangstation** [comment]
see: https://github.com/xxjwxc/gormt/pull/106
