### ISSUE TITLE
table_prefix 命令行参数不生效，只能使用config文件配置

### ISSUE THREAD

**Issue by jeffmingup** [xxjwxc/gormt#107]
![](https://tva1.sinaimg.cn/large/008eGmZEgy1gn4uptcwvfj31g40u07ib.jpg)
非常感谢，很好用的工具。
老哥能不能支持下单表输出啊。数据库没有加外键约束，gorm想用关联需要手动修改strcut，不能直接覆盖，每次生成出来搜索复制有些麻烦。

**Comment by xxjwxc** [comment]
单表输出 可以使用ui模式复制。外键约束是支持的。
![image](https://user-images.githubusercontent.com/9114492/106278267-67f90200-6275-11eb-9501-5de80624b03e.png)
外键类似
![image](https://user-images.githubusercontent.com/9114492/106278409-a393cc00-6275-11eb-8557-f7e9be44eeff.png)

**Comment by xxjwxc** [comment]
命令行有什么地方使用不方便的，欢迎提PR。

**Comment by jeffmingup** [comment]
> 单表输出 可以使用ui模式复制。外键约束是支持的。
> ![image](https://user-images.githubusercontent.com/9114492/106278267-67f90200-6275-11eb-9501-5de80624b03e.png)
> 外键类似
> ![image](https://user-images.githubusercontent.com/9114492/106278409-a393cc00-6275-11eb-8557-f7e9be44eeff.png)

感谢回复。我可能没有说清楚，我这里数据库中是没有设置外键的，这样是不是就没有办法生成关联了。

**Comment by xxjwxc** [comment]
https://github.com/xxjwxc/gormt/issues/101
跟这个问题一样，我最近将添加：注释注解方式支持自定义外键。请留意更新。(应该会很快)

**Comment by xxjwxc** [comment]
https://github.com/xxjwxc/gormt/commit/689c8a30d9ba14bbe3df901e66bd9f0a1f05551f

已添加：注释前请加入[@fk tablename.columnname] 来配置自定义外键
