### ISSUE TITLE
不支持smallint类型

### ISSUE THREAD

**Issue by android-coco** [xxjwxc/gormt#11]
{"Host":"127.0.0.1","Port":3306,"Username":"root","Password":"123456","Database":"xjaccountsdb"}
panic: type (smallint(6)) not match in any way.maybe need to add on ()

**Comment by xxjwxc** [comment]
您好：类型没有完全映射完。如果有错误，需要在
https://github.com/xxjwxc/gormt/blob/master/data/view/cnf/def.go
中补充：

**Comment by xxjwxc** [comment]
欢迎PR补充

**Comment by android-coco** [comment]
ok

**Comment by xxjwxc** [comment]
我做了稍微的调整：请审阅：
https://github.com/xxjwxc/gormt/blob/master/data/view/cnf/def.go

commit：
https://github.com/xxjwxc/gormt/commit/9617450e6b4129bb675701a7d8dbcfb834c73987

**Comment by android-coco** [comment]
ok
