### ISSUE TITLE
能否提供针对json tag的命名规则扩展，比如可以设置json tag采用小驼峰或者下划线的方式

### ISSUE THREAD

**Issue by JaminCui** [xxjwxc/gormt#113]
如题

**Comment by xxjwxc** [comment]
最开始是支持的，但后边为了精简就去掉了，目前是用golang默认的命名方式，goline不会报警报

**Comment by JaminCui** [comment]
那如果要加上这个需要在哪里改源码呢，跟前端交互基本都是小驼峰了，这个特性很重要才对啊

**Comment by xxjwxc** [comment]
可以加我一下微信不？jnpher

**Comment by xxjwxc** [comment]
已更新：
https://github.com/xxjwxc/gormt/commit/a095bb9869882551624c20649c04b0268186250b
