### ISSUE TITLE
生成函数注释错误

### ISSUE THREAD

**Issue by 1379** [xxjwxc/gormt#121]
// GetBatchFromURL 批量唯一主键查找
func (obj *_PostsMgr) GetBatchFromURL(urls []string) (results []*Posts, err error) {
	err = obj.DB.WithContext(obj.ctx).Table(obj.GetTableName()).Where("url IN (?)", urls).Find(&results).Error

	return
}

上面是生成的函数，然而我的数据库中url字段并不是主键，也不是索引，所以这个注释是不是有问题

**Comment by xxjwxc** [comment]
是的：data\view\genfunc\def.go#198行需要改一下注释

**Comment by 1379** [comment]
那我提个pr改一下吧，可以吗

**Comment by xxjwxc** [comment]
ok,
