### ISSUE TITLE
配置文件是否考虑新增自定义字段类型映射？

### ISSUE THREAD

**Issue by pengwenwu** [xxjwxc/gormt#123]
需求是：比如mysql字段类型 datetime、date、time等类型，默认生成的struct都是time.time类型。
但是会有自定义类型的需求，比如针对datetime做了额外的处理，是否可以根据配置文件自定义？

**Comment by xxjwxc** [comment]
这个提议可以，

**Comment by pengwenwu** [comment]
目前是拉了作者的源代码，自行修改了下，上传到内部仓库。主要升级了以下几个方面：
1. 自定义mysql数据类型映射
2. 自定义生成输出文件名
3. 自定义json tag类型，支持下划线和小驼峰

主要只改了可执行文件生成部分，对于gui方便会有遗漏，所以并未merge_request。感谢作者。

**Comment by xxjwxc** [comment]
@pengwenwu 非常好，如果有好的功能，希望能一起完善这个工具。

**Comment by pengwenwu** [comment]
> @pengwenwu 非常好，如果有好的功能，希望能一起完善这个工具。

已提交pull request。
可能命名不规范、或者gui相关代码未做处理，希望可以帮忙完善一下

**Comment by xxjwxc** [comment]
好的，我看了下，确实需要整理一下。

**Comment by xxjwxc** [comment]
做了一些小调整，https://github.com/xxjwxc/gormt/commit/01388f3b67f3d009a04fba4a61e5438724dc53ba

**Comment by pengwenwu** [comment]
> 做了一些小调整，[01388f3](https://github.com/xxjwxc/gormt/commit/01388f3b67f3d009a04fba4a61e5438724dc53ba)

非常感谢
