### ISSUE TITLE
为什么生成的代码什么标签都不带？比如gorm的标签和json的标签

### ISSUE THREAD

**Issue by liaosimin** [xxjwxc/gormt#13]
./../../../project/gormt/gormt -H 10.12.77.233 --port=3306 -u=mitra -p=shopee123! -d apc_report_db
		
type	ReportInfoTab	struct {		
Name	string	`gorm:"primary_key"`			
CsvURL	string				
Status	int8				
CronSchedule	string				
LastExecTime	time.Time				
CreateTime	time.Time				
UpdateTime	time.Time				
}

**Comment by xxjwxc** [comment]
你需要在配置文件中修改配置，
https://github.com/xxjwxc/gormt/blob/master/config.yml

**Comment by xxjwxc** [comment]
默认导出是简单模式。
请使用
gormt -h 查看启动参数

**Comment by xxjwxc** [comment]
Problem solved
