### ISSUE TITLE
不支持tinyint 么

### ISSUE THREAD

**Issue by No3ming** [xxjwxc/gormt#15]
` type (tinyint(2)) not match in any way.maybe need to add on ()`

**Comment by xxjwxc** [comment]
如果有不支持的类型：需要你添加到
https://github.com/xxjwxc/gormt/blob/master/data/view/cnf/def.go#11 （精确类型）
https://github.com/xxjwxc/gormt/blob/master/data/view/cnf/def.go#28 （模糊匹配类型）

欢迎 pull request 中完善。

**Comment by xxjwxc** [comment]
不过在：
https://github.com/xxjwxc/gormt/blob/master/data/view/cnf/def.go#28 模糊匹配

`^(tinyint)[(]\d+[)]`:     "int8",
有这个。我的可执行文件没有更新。需要重新编译一下

**Comment by xxjwxc** [comment]
6. build
make windows
make linux
make mac
编译
