### ISSUE TITLE
列名错误大小写问题

### ISSUE THREAD

**Issue by wclssdn** [xxjwxc/gormt#150]
数据表中有一列叫`customer_uid`，在生成go对象后，变成了`CustomerUId`。其中`uid`的`i`被错误的大写了。
期望的值应该是`CustomerUid`

**Comment by xxjwxc** [comment]
收到：我是参考 golint 来实现的，应该是有bug
源代码：https://github.com/golang/lint/blob/6edffad5e6160f5949cdefc81710b2706fbcd4f6/lint.go#L770
我实现的代码：https://github.com/xxjwxc/public/blob/58698748828996eea4efd4cba0beeeb5af6775b8/mybigcamel/def.go#L8
请参考

**Comment by xxjwxc** [comment]
@wclssdn 已经修改，请拉取最新版本，编译就好
customer_uid => CustomerUID

**Comment by wclssdn** [comment]
优秀~~~
