### ISSUE TITLE
生成的Condetion 是拼写错误码，是不是用Condition 更合适呢？

### ISSUE THREAD

**Issue by windha** [xxjwxc/gormt#155]
// 自定义sql查询
--
type Condetion struct {
list []*condetionInfo
 }
 
// And a condition by and .and 一个条件
 func (c *Condetion) And(column string, cases string, value ...interface{}) {

**Comment by xxjwxc** [comment]
@windha 对的，等你PR

**Comment by windha** [comment]
@xxjwxc 已经提交PR
