### ISSUE TITLE
如果表太多，内存不足

### ISSUE THREAD

**Issue by No3ming** [xxjwxc/gormt#16]
`panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1385c66]

goroutine 1 [running]:
database/sql.(*Rows).close(0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.12.8/libexec/src/database/sql/sql.go:2976 +0x66
database/sql.(*Rows).Close(0x0, 0xc0000a2d00, 0x0)
        /usr/local/Cellar/go/1.12.8/libexec/src/database/sql/sql.go:2972 +0x33
panic(0x14d4fc0, 0x1a1eea0)
        /usr/local/Cellar/go/1.12.8/libexec/src/runtime/panic.go:522 +0x1b5
database/sql.(*Rows).close(0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.12.8/libexec/src/database/sql/sql.go:2976 +0x66
database/sql.(*Rows).Close(0x0, 0xc0005078c0, 0x0)
        /usr/local/Cellar/go/1.12.8/libexec/src/database/sql/sql.go:2972 +0x33
panic(0x14d4fc0, 0x1a1eea0)
        /usr/local/Cellar/go/1.12.8/libexec/src/runtime/panic.go:522 +0x1b5
database/sql.(*Rows).close(0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.12.8/libexec/src/database/sql/sql.go:2976 +0x66
database/sql.(*Rows).Close(0x0, 0xc000507d60, 0x0)
        /usr/local/Cellar/go/1.12.8/libexec/src/database/sql/sql.go:2972 +0x33
panic(0x14d4fc0, 0x1a1eea0)
        /usr/local/Cellar/go/1.12.8/libexec/src/runtime/panic.go:522 +0x1b5
database/sql.(*Rows).close(0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.12.8/libexec/src/database/sql/sql.go:2976 +0x66
database/sql.(*Rows).Close(0x0, 0xc0006ffb80, 0x0)
        /usr/local/Cellar/go/1.12.8/libexec/src/database/sql/sql.go:2972 +0x33
panic(0x14d4fc0, 0x1a1eea0)
        /usr/local/Cellar/go/1.12.8/libexec/src/runtime/panic.go:522 +0x1b5
database/sql.(*Rows).close(0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.12.8/libexec/src/database/sql/sql.go:2976 +0x66
database/sql.(*Rows).Close(0x0, 0xc0006ffd00, 0x0)
        /usr/local/Cellar/go/1.12.8/libexec/src/database/sql/sql.go:2972 +0x33
panic(0x14d4fc0, 0x1a1eea0)
        /usr/local/Cellar/go/1.12.8/libexec/src/runtime/panic.go:522 +0x1b5
database/sql.(*Rows).close(0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.12.8/libexec/src/database/sql/sql.go:2976 +0x66
database/sql.(*Rows).Close(0x0, 0xc0006ffd60, 0x0)
        /usr/local/Cellar/go/1.12.8/libexec/src/database/sql/sql.go:2972 +0x33
panic(0x14d4fc0, 0x1a1eea0)
        /usr/local/Cellar/go/1.12.8/libexec/src/runtime/panic.go:522 +0x1b5
database/sql.(*Rows).close(0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.12.8/libexec/src/database/sql/sql.go:2976 +0x66
database/sql.(*Rows).Close(0x0, 0xc0007012e0, 0x0)
        /usr/local/Cellar/go/1.12.8/libexec/src/database/sql/sql.go:2972 +0x33
panic(0x14d4fc0, 0x1a1eea0)
        /usr/local/Cellar/go/1.12.8/libexec/src/runtime/panic.go:522 +0x1b5
database/sql.(*Rows).close(0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.12.8/libexec/src/database/sql/sql.go:2976 +0x66
database/sql.(*Rows).Close(0x0, 0xc0003f2c20, 0x0)
        /usr/local/Cellar/go/1.12.8/libexec/src/database/sql/sql.go:2972 +0x33
panic(0x14d4fc0, 0x1a1eea0)
        /usr/local/Cellar/go/1.12.8/libexec/src/runtime/panic.go:522 +0x1b5
database/sql.(*Rows).close(0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.12.8/libexec/src/database/sql/sql.go:2976 +0x66
database/sql.(*Rows).Close(0x0, 0xc0005581a0, 0x0)
        /usr/local/Cellar/go/1.12.8/libexec/src/database/sql/sql.go:2972 +0x33
panic(0x14d4fc0, 0x1a1eea0)
        /usr/local/Cellar/go/1.12.8/libexec/src/runtime/panic.go:522 +0x1b5
database/sql.(*Rows).close(0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.12.8/libexec/src/database/sql/sql.go:2976 +0x66
database/sql.(*Rows).Close(0x0, 0xc000558420, 0x0)
        /usr/local/Cellar/go/1.12.8/libexec/src/database/sql/sql.go:2972 +0x33
panic(0x14d4fc0, 0x1a1eea0)
        /usr/local/Cellar/go/1.12.8/libexec/src/runtime/panic.go:522 +0x1b5
database/sql.(*Rows).close(0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.12.8/libexec/src/database/sql/sql.go:2976 +0x66
database/sql.(*Rows).Close(0x0, 0xc0003f2e80, 0x0)
        /usr/local/Cellar/go/1.12.8/libexec/src/database/sql/sql.go:2972 +0x33
panic(0x14d4fc0, 0x1a1eea0)
        /usr/local/Cellar/go/1.12.8/libexec/src/runtime/panic.go:522 +0x1b5
database/sql.(*Rows).close(0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.12.8/libexec/src/database/sql/sql.go:2976 +0x66
database/sql.(*Rows).Close(0x0, 0xc000701ee0, 0x0)
        /usr/local/Cellar/go/1.12.8/libexec/src/database/sql/sql.go:2972 +0x33
panic(0x14d4fc0, 0x1a1eea0)
        /usr/local/Cellar/go/1.12.8/libexec/src/runtime/panic.go:522 +0x1b5
database/sql.(*Rows).close(0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.12.8/libexec/src/database/sql/sql.go:2976 +0x66
database/sql.(*Rows).Close(0x0, 0xc00052e300, 0x0)
        /usr/local/Cellar/go/1.12.8/libexec/src/database/sql/sql.go:2972 +0x33
panic(0x14d4fc0, 0x1a1eea0)
        /usr/local/Cellar/go/1.12.8/libexec/src/runtime/panic.go:522 +0x1b5
database/sql.(*Rows).close(0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.12.8/libexec/src/database/sql/sql.go:2976 +0x66
database/sql.(*Rows).Close(0x0, 0xc0003f36e0, 0x0)
        /usr/local/Cellar/go/1.12.8/libexec/src/database/sql/sql.go:2972 +0x33
panic(0x14d4fc0, 0x1a1eea0)
        /usr/local/Cellar/go/1.12.8/libexec/src/runtime/panic.go:522 +0x1b5
database/sql.(*Rows).close(0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.12.8/libexec/src/database/sql/sql.go:2976 +0x66
database/sql.(*Rows).Close(0x0, 0xc000558e40, 0x0)
        /usr/local/Cellar/go/1.12.8/libexec/src/database/sql/sql.go:2972 +0x33
panic(0x14d4fc0, 0x1a1eea0)
        /usr/local/Cellar/go/1.12.8/libexec/src/runtime/panic.go:522 +0x1b5
database/sql.(*Rows).close(0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.12.8/libexec/src/database/sql/sql.go:2976 +0x66
database/sql.(*Rows).Close(0x0, 0xc000559560, 0x0)
        /usr/local/Cellar/go/1.12.8/libexec/src/database/sql/sql.go:2972 +0x33
panic(0x14d4fc0, 0x1a1eea0)
        /usr/local/Cellar/go/1.12.8/libexec/src/runtime/panic.go:522 +0x1b5
database/sql.(*Rows).close(0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.12.8/libexec/src/database/sql/sql.go:2976 +0x66
database/sql.(*Rows).Close(0x0, 0xc0003f3980, 0x0)
        /usr/local/Cellar/go/1.12.8/libexec/src/database/sql/sql.go:2972 +0x33
panic(0x14d4fc0, 0x1a1eea0)
        /usr/local/Cellar/go/1.12.8/libexec/src/runtime/panic.go:522 +0x1b5
database/sql.(*Rows).close(0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.12.8/libexec/src/database/sql/sql.go:2976 +0x66
database/sql.(*Rows).Close(0x0, 0xc000428080, 0x0)
        /usr/local/Cellar/go/1.12.8/libexec/src/database/sql/sql.go:2972 +0x33
panic(0x14d4fc0, 0x1a1eea0)
        /usr/local/Cellar/go/1.12.8/libexec/src/runtime/panic.go:522 +0x1b5
database/sql.(*Rows).close(0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.12.8/libexec/src/database/sql/sql.go:2976 +0x66
database/sql.(*Rows).Close(0x0, 0xc0003f3e80, 0x0)
        /usr/local/Cellar/go/1.12.8/libexec/src/database/sql/sql.go:2972 +0x33
panic(0x14d4fc0, 0x1a1eea0)
        /usr/local/Cellar/go/1.12.8/libexec/src/runtime/panic.go:522 +0x1b5
database/sql.(*Rows).close(0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.12.8/libexec/src/database/sql/sql.go:2976 +0x66
database/sql.(*Rows).Close(0x0, 0xc0004282c0, 0x0)
        /usr/local/Cellar/go/1.12.8/libexec/src/database/sql/sql.go:2972 +0x33
`

**Comment by xxjwxc** [comment]
应该是bug。

**Comment by xxjwxc** [comment]
您这个不太像是gormt报出来的问题。可以加一个联系方式，具体看下吗？

**Comment by No3ming** [comment]
我的微信：dongmingloveyou

**Comment by xxjwxc** [comment]
已修复此问题
