### ISSUE TITLE
怎么这么多拼写错误。。。

### ISSUE THREAD

**Issue by 1379** [xxjwxc/gormt#160]
![image](https://user-images.githubusercontent.com/34785043/129508904-5792bd42-3e24-444d-a548-cc3691c28763.png)
![image](https://user-images.githubusercontent.com/34785043/129509112-7231bd6a-990d-47b3-8438-5f378997856b.png)

1. 注释不标准，甚至注释里函数名都没写对。。。三个函数注释没一个正确的。。。。
2. Condetion 是什么鬼？不应该是Condition吗

作者是不是自己用都没用过，这种ide都能检查出来的拼写错误为什么都会有。。。写出来骗star的？？

**Comment by xxjwxc** [comment]
请注意您的语言：
https://github.com/xxjwxc/gormt/blob/4ffb3e8ac3ce0ef29f720de6c4253361cc91e768/data/view/genfunc/def.go#L115

**Comment by xxjwxc** [comment]
一个人维护开源项时间还是有限，如遇到问题请PR吧。

**Comment by 1379** [comment]
sorry ,为我的过激语言道歉。
但是我觉得拼写问题实在是最低级的错误，希望大家一起努力吧

**Comment by 1379** [comment]
@xxjwxc 问一下，Mgr是什么的缩写呢

**Comment by xxjwxc** [comment]
manager

**Comment by xxjwxc** [comment]
manager
