### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by ClearWang** [xxjwxc/gormt#17]
大神，你这个文档写的看完也不知道怎么用，我的理解是：1.配置好yml 2.go build根目录下的main.go 但是貌似会编译失败  提示：go: github.com/go-playground/universal-translator@v0.17.0: Get https://proxy.golang.org/github.com/go-playground/universal-translator/@v/v0.17.0.mod: dial tcp [2404:6800:4008:803::2011]:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. 求大神回复指导下

**Comment by xxjwxc** [comment]
hello，请给我一个联系方式。

**Comment by ClearWang** [comment]
18788828038@163.com 感谢

**Comment by xxjwxc** [comment]
看起来是您的go mod问题。可能需要做一个：export GOPROXY=https://goproxy.cn
国内代理

**Comment by xxjwxc** [comment]
可以在根目录使用：
make windows
make linux
make mac
编译。

**Comment by ClearWang** [comment]
确实是这个问题 添加环境变量后就ok了 nice~！还发现了一个问题 对于db如果不设置密码访问  是会出错的

**Comment by xxjwxc** [comment]
good feedback. 
如果不用密码：请修改：
https://github.com/xxjwxc/gormt/blob/master/data/config/MyIni.go#22 
为 
Password string
去掉后边的： `validate:"required"`

请帮忙测试一下，如果通过，请PR，


last.
Please feel free to fork and PR if you find any updates, issues or improvement.
