### ISSUE TITLE
建议:关于自动生成切片复数type定义及相关简单的方法

### ISSUE THREAD

**Issue by cpj555** [xxjwxc/gormt#172]
![image](https://user-images.githubusercontent.com/19289096/140468907-89694dcb-f7e1-4d3a-b626-fe4acf38966d.png)
目前我只会gormt生成数据库实体,很方便。
很多业务场景下都是查出list去操作，代码又要复制一遍这种类似的就是list转hash键值然后去get的操作,不知道后期有没有计划加入呢

**Comment by xxjwxc** [comment]
没太明白意思
