### ISSUE TITLE
./gormt -H=127.0.0.1 -d=oauth_db -p=qwer -u=root --port=3306

### ISSUE THREAD

**Issue by lizuoqiang** [xxjwxc/gormt#173]
`
panic: type (year(4)) not match in any way.maybe need to add on (https://github.com/xxjwxc/gormt/blob/master/data/view/cnf/def.go)

goroutine 1 [running]:
github.com/xxjwxc/gormt/data/view/model.getTypeName(0xc0001d4a29, 0x7, 0x4779d01, 0x1, 0x4737c7c)
	/Users/xxj/work/workspace/github/xxjwxc/gormt/data/view/model/common.go:88 +0x785
github.com/xxjwxc/gormt/data/view/model.(*_Model).genTableElement(0xc00079fc28, 0xc000230000, 0xc, 0x11, 0x9, 0xc000028ae0, 0x9)
`

**Comment by lizuoqiang** [comment]
year类型不支持

**Comment by xxjwxc** [comment]
https://github.com/xxjwxc/gormt/blob/master/data/view/cnf/def.go
需要在这里添加映射关系
