### ISSUE TITLE
如何获取最新的gormt执行文件？

### ISSUE THREAD

**Issue by LouZon** [xxjwxc/gormt#186]
我需要用到最新修复的“修复了当表字段类型为datetime或者time并且默认为NULL时，在结构中没有被设置成指针类型的问题”这个特性，但是下载页面中的gormt执行文件并没有同步更新到最新版本，把代码直接clone下来跑又有很多wingw环境的问题，请问下载页面中会更新最新的gormt.exe吗

**Comment by xxjwxc** [comment]
稍等，我更新一个版本

**Comment by xxjwxc** [comment]
已经更新：
https://github.com/xxjwxc/gormt/releases/tag/v2.1.gorm
