### ISSUE TITLE
string pointer not working as expected

### ISSUE THREAD

**Issue by rudiwawa** [xxjwxc/gormt#193]
the code below is the result generated from **gormt**.
in the database string **nulllable**, but generate from gormt does **not use pointers**.
but the integer is as expected, the nullable integer uses a pointer

![image](https://user-images.githubusercontent.com/26498067/148880229-72f31155-0f4c-4a97-86e1-56e137cbbf3e.png)

**Comment by xxjwxc** [comment]
need add string in 
https://github.com/xxjwxc/gormt/blob/d371cfed631784f692bf5affdf64b061a6571ce0/data/view/model/common.go#L92

**Comment by rudiwawa** [comment]
okay if that's the case, thank you very much

**Comment by rudiwawa** [comment]
you just updated gormt and i have used so it can be a string pointer, you saved my life thanks
