### ISSUE TITLE
the result of generating id with UUID type is not as expected

### ISSUE THREAD

**Issue by rudiwawa** [xxjwxc/gormt#194]
my database uses uuid, but why does the generated gormt code use gorm.model? while gorm.model the ID type is int while in the database it uses string

![image](https://user-images.githubusercontent.com/26498067/148880514-ec416a92-5edf-4cd9-b600-b3f93fb5e265.png)
![image](https://user-images.githubusercontent.com/26498067/148880557-dcba62bb-1cf8-4c3f-b604-92f5cab10a29.png)

**Comment by xxjwxc** [comment]
![image](https://user-images.githubusercontent.com/9114492/148882016-729441e8-4f9f-4fb0-bb29-5ca9de575546.png)

这三个同时存在，会变成gorm.model。这是gorm标准

**Comment by rudiwawa** [comment]
okay if that's the case, thank you very much
