### ISSUE TITLE
Missing references

### ISSUE THREAD

**Issue by rudiwawa** [xxjwxc/gormt#195]
no references as a condition for preload gorm
gormt result
![image](https://user-images.githubusercontent.com/26498067/149251433-92182f37-3d47-4500-a37b-8c0ed2fb2298.png)
expected
![image](https://user-images.githubusercontent.com/26498067/149251471-edd39137-771b-43de-a951-455edeed972b.png)

**Comment by xxjwxc** [comment]
ok

**Comment by xxjwxc** [comment]
done
https://github.com/xxjwxc/gormt/commit/d744f25b88713ad4dc5b61791a12f8382bf3eaa4

**Comment by rudiwawa** [comment]
ok thank you very much, gormt makes my job very easy
