### ISSUE TITLE
this is my question，what should i do

### ISSUE THREAD

**Issue by zilinyo** [xxjwxc/gormt#20]
goroutine 1 [running]:
github.com/xxjwxc/gormt/data/view/model.getTypeName(0xc0003fc790, 0x8, 0x1560455, 0x1)
        /Users/apple/go/src/github.com/xxjwxc/gormt/data/view/model/common.go:47 +0x218
github.com/xxjwxc/gormt/data/view/model.(*_Model).genTableElement(0xc000555cf8, 0xc00047a000, 0x14, 0x27, 0xc00014a700, 0x7, 0x8)
        /Users/apple/go/src/github.com/xxjwxc/gormt/data/view/model/model.go:46 +0xc44
github.com/xxjwxc/gormt/data/view/model.(*_Model).generate(0xc000555cf8, 0x7ffeefbffab8, 0x6)
        /Users/apple/go/src/github.com/xxjwxc/gormt/data/view/model/model.go:29 +0x1f9
github.com/xxjwxc/gormt/data/view/model.Generate(...)
        /Users/apple/go/src/github.com/xxjwxc/gormt/data/view/model/model.go:19
github.com/xxjwxc/gormt/data/view/gtools.Execute()
        /Users/apple/go/src/github.com/xxjwxc/gormt/data/view/gtools/gtools.go:25 +0x14a
github.com/xxjwxc/gormt/data/cmd.glob..func1(0x1a41e60, 0xc00033e420, 0x0, 0x6)
        /Users/apple/go/src/github.com/xxjwxc/gormt/data/cmd/cmd.go:27 +0x20
github.com/spf13/cobra.(*Command).execute(0x1a41e60, 0xc0000b0010, 0x6, 0x6, 0x1a41e60, 0xc0000b0010)

**Comment by xxjwxc** [comment]
可以加个联系方式吗？具体我看下问题。这个里面似乎看不到问题所在？
或者是当前目录是否有个err文件？

**Comment by xxjwxc** [comment]
可以加个联系方式吗？具体我看下问题。这个里面似乎看不到问题所在？
或者是当前目录是否有个err文件？

**Comment by zilinyo** [comment]
qq 564925591

**Comment by zilinyo** [comment]
> 可以加个联系方式吗？具体我看下问题。这个里面似乎看不到问题所在？
> 或者是当前目录是否有个err文件？

qq:564925591

**Comment by xxjwxc** [comment]
需要验证你邮箱地址

**Comment by xxjwxc** [comment]
看您错误点可能是类型没找到。可能要完善一下类型
![image](https://user-images.githubusercontent.com/9114492/69915619-0b8d2d80-148c-11ea-96c2-958242c25109.png)

**Comment by zilinyo** [comment]
确实是有的类型不支持

**Comment by xxjwxc** [comment]
希望你能提供panic详细信息，好完善支持更多类型。
https://github.com/xxjwxc/gormt/blob/master/data/view/cnf/def.go
在这里完善类型。

**Comment by zilinyo** [comment]
longtext  现在发现一个不支持~~

**Comment by zilinyo** [comment]
能加一下您 qq吗

**Comment by xxjwxc** [comment]
您可以提一个PR过来吗？
https://github.com/xxjwxc/gormt/blob/master/data/view/cnf/def.go
里面一个精确匹配，一个模糊匹配。
我qq：346944475
