### ISSUE TITLE
gen.base.go 和其他 Mgr 文件怎么放到不同的 package 下

### ISSUE THREAD

**Issue by zcyc** [xxjwxc/gormt#207]
有些架构对文件摆放有强制要求，请问大佬怎么把它们放在不同目录。_BaseMgr 这个前边 _ 的意义是什么。

**Comment by zcyc** [comment]
_BaseMgr 这个前边 _ 的意义是什么。

**Comment by xxjwxc** [comment]
基础公共函数！_表示内部函数

**Comment by zcyc** [comment]
但是这样的话就不能在其他 package 里边引用了。
