### ISSUE TITLE
model是否使用gorm.Model配置文件这个示例是不是写错了

### ISSUE THREAD

**Issue by wxd1343401** [xxjwxc/gormt#208]
<img width="689" alt="image" src="https://user-images.githubusercontent.com/41733401/161362526-16549802-3151-4bd3-821f-8e9c8305bff9.png">

**Comment by wxd1343401** [comment]
user_gorm_model

**Comment by leonzai** [comment]
@wxd1343401 感谢提出，困扰我良久，希望作者及时更改下

**Comment by jiang4869** [comment]
@leonzai 已经修复

**Comment by qikong333** [comment]
<img width="510" alt="image" src="https://user-images.githubusercontent.com/23370805/165239093-2c5d10fb-e76f-4a1b-ad10-9ff6cd05a690.png">
直接下载的mac版本里面还是use_gorm_model

**Comment by xxjwxc** [comment]
好的，收到

**Comment by xxjwxc** [comment]
已更新！@[qikong333](https://github.com/qikong333)
