### ISSUE TITLE
是否会考虑将id生成为Id，而不是全部大写

### ISSUE THREAD

**Issue by tnngo** [xxjwxc/gormt#210]
是否会考虑增加一个配置功能，将id生成为Id，而不是全部大写。考虑到protobuf生成带id的字段都是Id，仅I大写。

这样可以更好的利用`copier.Copy()`方法，该方法来自`github.com/jinzhu/copier`包，作用是同名字段可直接赋值。

**Comment by tnngo** [comment]
谢谢，已解决

**Comment by wmvm0** [comment]
> 谢谢，已解决

怎么解决的呢，我也想用 Id

**Comment by wmvm0** [comment]
> > 谢谢，已解决
> 
> 怎么解决的呢，我也想用 Id

没事了，已解决
