### ISSUE TITLE
表字段名全为大写时,转换为struct时,是否可以增加驼峰转换方式.

### ISSUE THREAD

**Issue by carlye** [xxjwxc/gormt#211]
mysql数据库ddl 

CREATE TABLE T_USER (
  ID      varchar(50), 
  NAME    varchar(50), 
  ACCOUNT varchar(50), 
  TITLE   varchar(50),
  CREATE_TIME datetime NULL
) CHARACTER SET utf8mb4;

转换完的字段为

// TUser [...]		
type	TUser	struct {		
ID	string	`gorm:"column:ID;type:varchar(50);default:null"`			
NAME	string	`gorm:"column:NAME;type:varchar(50);default:null"`			
ACCOUNT	string	`gorm:"column:ACCOUNT;type:varchar(50);default:null"`			
TITLE	string	`gorm:"column:TITLE;type:varchar(50);default:null"`	
CREATETIME time.Time	`gorm:"column:CREATE_TIME;type:datetime;default:null"`				
}

期望能够转换成
type	TUser	struct {		
Id string	`gorm:"column:ID;type:varchar(50);default:null"`			
Name string	`gorm:"column:NAME;type:varchar(50);default:null"`			
Account string	`gorm:"column:ACCOUNT;type:varchar(50);default:null"`			
Title	string	`gorm:"column:TITLE;type:varchar(50);default:null"`	
CreateTime time.Time	`gorm:"column:CREATE_TIME;type:datetime;default:null"`			
}

请问可有相关的办法?

**Comment by xxjwxc** [comment]
可以的，解决方案，先做一下表明小写，再驼峰！我记下来了，会尽快更新掉

**Comment by xxjwxc** [comment]
已经更新：
https://github.com/xxjwxc/gormt/commit/11d9a6a6fab4e01cd0de7a3bfe3e8e504e231e04

**Comment by carlye** [comment]
@xxjwxc 武威,yyds! 一觉起来大神已经更新过了,太棒了！
