### ISSUE TITLE
能否实现生成的代码支持动态配置库

### ISSUE THREAD

**Issue by coverthesea** [xxjwxc/gormt#217]
业务上面经常出现一个情况就是，分库，可不可以在获取Mgr的时候，能够传输一个参数，选定不同的库
之前我用db.Table进行动态数据库的配置
由于现在Mgr里面已经有一个db.Table了，所以我从外面设置db.Table再传进来也不管用
不知道如何解决这种情况

**Comment by xxjwxc** [comment]
可以设置的：
![image](https://user-images.githubusercontent.com/9114492/179720526-a9824181-d983-4ba3-a323-927bb719d674.png)
类似这种
构造一个mgr对象
