### ISSUE TITLE
通过gormt生成的model autoIncrement tag会被type tag覆盖。

### ISSUE THREAD

**Issue by NadiaSama** [xxjwxc/gormt#218]
```go
type TestRecord struct {
	ID                  uint64  `gorm:"autoIncrement:true;primaryKey;column:id;type:bigint(20) unsigned;not null" json:"id"`
}
```
以MYSQL为例在生成sql时 `autoIncrement:true` 会给`ID column datatype·追加`AUTO_INCREMENT`。

而`type:bigint(20) unsigned;not null`会给`ID column datatype`设置`bigint(20) unsigned NOT NULL`，而且由于`type` 指定了`specified database data type`按照目前gorm的规则应给是`specificed database data type`会覆盖掉其他`datatype`设置，这导致之前的`AUTO_INCREMENT`被覆盖。

**Comment by NadiaSama** [comment]
如果column设置了`specificed database data type`且设置了自增，可以把`AUTO_INCREMENT`追加到`type` tag

**Comment by NadiaSama** [comment]
`not null` tag不会被覆盖。

**Comment by NadiaSama** [comment]
我现在gorm提个Issue看能不能给修复

**Comment by xxjwxc** [comment]
好的，这里也可以提pr，我来覆盖

**Comment by NadiaSama** [comment]
> 我先在gorm提个Issue看能不能给修复

问题找到了是通过gorm链接mysql使用的dialector有问题导致，这个问题已经被处理 https://github.com/go-gorm/mysql/pull/83
