### ISSUE TITLE
新版的没有UI界面了吗

### ISSUE THREAD

**Issue by 1542254356** [xxjwxc/gormt#22]
新版的没有UI界面了吗

**Comment by xxjwxc** [comment]
新版没有更新UI界面。ui界面是用mfc 做的。新版也不怎么需要了。
ui界面主要对单张表操作吧。如果您有兴趣更新，我可以把源码发您。

**Comment by 1542254356** [comment]
噢噢，现在最新版只能生成所有表吗，有生成单个表的方法吗

**Comment by 1542254356** [comment]
等我考试完了我试试用go做个界面，mfc没写过

**Comment by xxjwxc** [comment]
单个表没有。是一次性生成的。

**Comment by xxjwxc** [comment]
![ui_cn](https://user-images.githubusercontent.com/9114492/72866008-cdd2b580-3d14-11ea-86f8-43627a366739.gif)
界面模式已经添加。

**Comment by xxjwxc** [comment]
Problem solved
