### ISSUE TITLE
从sqlite3中获取表结构时候报错

### ISSUE THREAD

**Issue by leonscriptcc** [xxjwxc/gormt#220]
作者你好，gormt是个很棒的工具！我成功的导出了mysql的表结构
但是我在操作sqlite数据库的时候，出现了以下的错误：
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/76414767/191468519-e5d4713b-5a8c-4f2c-b478-0c59b6960f03.png">

我是直接使用gormt指令启动的

我的配置如下：
<img width="764" alt="image" src="https://user-images.githubusercontent.com/76414767/191468762-b62955cf-0cc1-4895-84dd-732cd6b19463.png">

**Comment by xxjwxc** [comment]
看错误信息，integer 类型没有定义，可以再config添加自定义，或者根据错误信息添加代码

**Comment by leonscriptcc** [comment]
> 

谢谢您的回复！我明白是怎么回事了～
再次感谢！
