### ISSUE TITLE
 type (geometry) not match in any way.maybe need to add on

### ISSUE THREAD

**Issue by 562122362** [xxjwxc/gormt#234]
![image](https://github.com/xxjwxc/gormt/assets/30225668/38150e29-7f28-44a9-87ae-63264467493f)

**Comment by xxjwxc** [comment]
添加自定义类型

**Comment by xxjwxc** [comment]
https://github.com/xxjwxc/gormt/commit/be65321744f3822153be25a434f31bd038a89d1f
已添加
