### ISSUE TITLE
是否支持导单表的结构

### ISSUE THREAD

**Issue by dryyun** [xxjwxc/gormt#25]
是否支持导单表的结构，而不是整个数据库，我看配置里面没类似的选项

**Comment by xxjwxc** [comment]
单表请使用这个工具：
https://github.com/xxjwxc/gormt/releases/download/v1.1.0/v1.0.zip

或者将config.yml 中  设置
is_out_func : false # 是否输出 快捷函数
 is_foreign_key : false # 是否导出外键关联

导出来之后可以选择单表结构。

**Comment by xxjwxc** [comment]
![ui_cn](https://user-images.githubusercontent.com/9114492/72865957-ab409c80-3d14-11ea-9457-979558a6aa92.gif)
已经支持
