### ISSUE TITLE
singular_table参数实际效果影响了表映射出来的结构体名称，而不是表名复数。

### ISSUE THREAD

**Issue by lgh-dev** [xxjwxc/gormt#29]
![image](https://user-images.githubusercontent.com/17794996/74600060-99110e80-50c6-11ea-8161-99435cf7b1c7.png)

false:
![image](https://user-images.githubusercontent.com/17794996/74600094-1b013780-50c7-11ea-8267-017eb1cd024c.png)
true:
![image](https://user-images.githubusercontent.com/17794996/74600100-310ef800-50c7-11ea-8281-de9e8670fdc3.png)

**Comment by xxjwxc** [comment]
是的，感谢，我近期将修复这个问题。

**Comment by xxjwxc** [comment]
hello。表名复数问题已修复。请采纳。

**Comment by xxjwxc** [comment]
[commit](https://github.com/xxjwxc/gormt/commit/6b14d480f0e1782fb91721657f7c28878ac88265)

**Comment by xxjwxc** [comment]
done.
