### ISSUE TITLE
mac使用终端无法复制生产的结构体

### ISSUE THREAD

**Issue by EthanChenLi** [xxjwxc/gormt#30]
macos  10.15
使用终端  ./gormt -g=true 输入设置内容输入框点不动，弹出框无法点击。
生产的结构体无法复制。

**Comment by xxjwxc** [comment]
收到，我将提供一个剪切板功能

**Comment by xxjwxc** [comment]
剪切板功能已添加，
![image](https://user-images.githubusercontent.com/9114492/75032056-99ecda80-54e2-11ea-9c3c-e4d1e47f1ec7.png)

**Comment by EthanChenLi** [comment]
感谢重视

**Comment by EthanChenLi** [comment]
请问怎么将生产的结构体添加到剪辑版

**Comment by xxjwxc** [comment]
![image](https://user-images.githubusercontent.com/9114492/78233522-76b54200-7508-11ea-8732-c4b398c31d1e.png)
选中列表，然后带紧急复制到剪切板。就ok了。
