### ISSUE TITLE
不支持类型tinyint

### ISSUE THREAD

**Issue by CXeon** [xxjwxc/gormt#32]
panic: type (tinyint) not match in any way.maybe need to add on (https://github.com/xxjwxc/gormt/blob/master/data/view/cnf/def.go)

**Comment by xxjwxc** [comment]
你看错误信息，希望能提pull request ,完善类型，谢谢。

**Comment by xxjwxc** [comment]
已经支持了。

**Comment by CXeon** [comment]
> 已经支持了。

纳尼，好的哈哈哈哈。

**Comment by xxjwxc** [comment]
Problem solved
