### ISSUE TITLE
不支持time类型

### ISSUE THREAD

**Issue by wjwyz** [xxjwxc/gormt#35]
panic: type (time) not match in any way.maybe need to add on (https://github.com/xxjwxc/gormt/blob/master/data/view/cnf/def.go)

**Comment by xxjwxc** [comment]
是的，https://github.com/xxjwxc/gormt/blob/master/data/view/cnf/def.go 
在：TypeMysqlDicMp 中添加一个time mapping吧。
希望提交PR 完善类型，thx

**Comment by xxjwxc** [comment]
已支持
