### ISSUE TITLE
MAC 上无论怎么设置 is_json_tag: true都无法导出带json的信息

### ISSUE THREAD

**Issue by qiuwenyuan1992** [xxjwxc/gormt#36]
命令行配置：☁  gormt [master] ⚡ ./gormt -H=127.0.0.1 -d=diddd -p=12345 -u=root --port=3306  is_json_tag=true                                        
窗口配置   is_json_tag: true

**Comment by xxjwxc** [comment]
is_url_tag:true
and url_tag:json

**Comment by xxjwxc** [comment]
sorry : 配置文件有变化。忘记更新上去了
is_web_tag:true
and url_tag:json

**Comment by xxjwxc** [comment]
Problem solved
