### ISSUE TITLE
panic: type (tinyint(2) unsigned) not match in any way.

### ISSUE THREAD

**Issue by Smelly-calf** [xxjwxc/gormt#37]
不支持这种类型

**Comment by xxjwxc** [comment]
需要在：
https://github.com/xxjwxc/gormt/blob/master/data/view/cnf/def.go#41
添加一行
`^(tinyint)[(]\d+[)] unsigned`:     "uint8",
请帮忙提交一个RP 完善，thx

**Comment by xxjwxc** [comment]
已支持
