### ISSUE TITLE
panic: type (binary(128)) not match in any way. 且不支持指定表格吗？

### ISSUE THREAD

**Issue by hexingjie** [xxjwxc/gormt#38]
panic: type (binary(128)) not match in any way. 且不支持指定表格吗？我不想导出整个db的表格……

**Comment by xxjwxc** [comment]
你使用gui模式可以复制单表。

https://github.com/xxjwxc/gormt/blob/master/data/view/cnf/def.go
在：TypeMysqlDicMp 中添加一个 time mapping 吧。
希望提交 PR 完善类型，thx

**Comment by hexingjie** [comment]
> 你使用gui模式可以复制单表。
> 
> https://github.com/xxjwxc/gormt/blob/master/data/view/cnf/def.go
> 在：TypeMysqlDicMp 中添加一个 time mapping 吧。
> 希望提交 PR 完善类型，thx

 不可以支持指定表名生成结构吗？如果我的db里面有很多表

**Comment by xxjwxc** [comment]
这个目前还没有。

**Comment by hexingjie** [comment]
可以支持下哇～

**Comment by xxjwxc** [comment]
binary (128) 已支持。单表还是使用gui模式吧。
