### ISSUE TITLE
tinyint(4)

### ISSUE THREAD

**Issue by taobaohi** [xxjwxc/gormt#4]
panic: type (tinyint(4)) not match in any way.

**Comment by xxjwxc** [comment]
you can update [def.go](https://github.com/xxjwxc/gormt/blob/master/data/view/gtools/def.go) file .
in TypeDicMp to add one case.
like 
`
//TypeDicMp 精确匹配类型
var TypeDicMp = map[string]string{
	"int":                 "int",
	"bigint":              "int64",
	"varchar":             "string",
	"char":                "string",
	"datetime":            "time.Time",
	"tinyint(1)":          "bool",
	"tinyint(1) unsigned": "bool",
         "tinyint(1)":          "int8",
	"json":                "string",
	"text":                "string",
	"timestamp":           "time.Time",
}
`
wait for your pull requests.

**Comment by xxjwxc** [comment]
done.

**Comment by xxjwxc** [comment]
done.
