### ISSUE TITLE
无法生成json tag

### ISSUE THREAD

**Issue by erosiners** [xxjwxc/gormt#40]
工具很好用，但是遇见个问题
如果下图配置，始终生成不了json tag，是我配置有问题吗？
![image](https://user-images.githubusercontent.com/6299779/78747034-ff196400-799a-11ea-9530-ff70fd1c8a02.png)
![image](https://user-images.githubusercontent.com/6299779/78747087-2839f480-799b-11ea-811c-43868ee84c15.png)

**Comment by xxjwxc** [comment]
is_web_tag:true
and url_tag:json

**Comment by xxjwxc** [comment]
![image](https://user-images.githubusercontent.com/9114492/78747615-64ba2000-799c-11ea-8bc8-48266a77a0c0.png)
按照这个配置就行。因为支持了多种tag标记。所以配置文件有变化

**Comment by erosiners** [comment]
> ![image](https://user-images.githubusercontent.com/9114492/78747615-64ba2000-799c-11ea-8bc8-48266a77a0c0.png)
> 按照这个配置就行。因为支持了多种tag标记。所以配置文件有变化

非常感谢，已经可以了，还是看文档不认真，尴尬呀
