### ISSUE TITLE
不支持数据库是空密码

### ISSUE THREAD

**Issue by igo9go** [xxjwxc/gormt#41]
error info:  Key: 'MysqlDbInfo.Password' Error:Field validation for 'Password' failed on the 'required' tag Key: 'MysqlDbInfo.Password' Error:Field validation for 'Password' failed on the 'required' tag

**Comment by xxjwxc** [comment]
![image](https://user-images.githubusercontent.com/9114492/78884923-4af90580-7a8e-11ea-8cd2-73afd35d360f.png)
已经支持了，请下载最新版、

**Comment by xxjwxc** [comment]
Problem solved
