### ISSUE TITLE
GetByOption/GetByOptions系列函数功能无效

### ISSUE THREAD

**Issue by jet-xita** [xxjwxc/gormt#42]
win10环境下，在gin这个web server下引入gormt生成的代码，调用方式跟测试案例类似，即：
userMgr := model.UserMgr(db)
userMgr.GetByOption(userMgr.WithAccount("aa"), userMgr.WithPwd("bb"))
发觉返回数据不正确，经调试，发觉GetByOption函数内部，调用apply的时候，拿不到传入进去的参数"aa"和"bb"，调试查看变量的时候，提示报错 error code 299—— Only part of a ReadProcessMemory or WriteProcessMemory request was completed。而且最终得到的options.options这个map里存在Account和Pwd的key，但是里面的内容都是""，不知道具体是什么原因。

**Comment by jet-xita** [comment]
感觉会跟闭包的实现有关系？似乎在我这里，闭包里的Account和Pwd访问不了，然后导致数据赋空

**Comment by xxjwxc** [comment]
可以要一个联系方式吗？跟你具体调试下

**Comment by xxjwxc** [comment]
@jet-xita 

> 感觉会跟闭包的实现有关系？似乎在我这里，闭包里的Account和Pwd访问不了，然后导致数据赋空
应该不是闭包问题。需要看你调用实现

**Comment by jet-xita** [comment]
很抱歉，问题原来是因为磁盘空间用光引起的，清理了空间之后，再调用就可以了，跟代码没有关系。

**Comment by xxjwxc** [comment]
ok
