### ISSUE TITLE
数据表主键名称为id，为什么生成的表结构中，该字段的jason标志为空？

### ISSUE THREAD

**Issue by jet-xita** [xxjwxc/gormt#43]
type User struct {
	ID      int    `gorm:"primary_key;column:id;type:int(10) unsigned;not null" json:"-"` // ID
	Account string `gorm:"column:account;type:varchar(255);not null" json:"account"`      // 账号
}

===============
如上，为什么" json:"-"` // ID，这样的话该结构序列化时，无法生成该字段，怎么解决？

**Comment by xxjwxc** [comment]
id 默认不导出

**Comment by xxjwxc** [comment]
我觉得你这个建议比较好，应该有配置允许导出。后边我加上这个功能，你也可以提交pr

**Comment by evildao** [comment]
我也觉着隐藏没必要，而且代码里只限制了id关键字也不是很好

**Comment by xxjwxc** [comment]
Problem solved
