### ISSUE TITLE
当表名为order或者match时，无法生成对应的struct

### ISSUE THREAD

**Issue by hutu1st** [xxjwxc/gormt#49]
以下为程序生成的日志：
(/Users/jianghongchao/Downloads/gormt-master/data/view/model/genmysql/genmysql.go:113)		[2020-04-30 15:59:20]	 [Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'match' at line 1]
goroutine 18 [running]:
runtime/debug.Stack(0xc0000119a0, 0xc0002ac6c0, 0x116)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/xxjwxc/public/mylog.SaveError(0xc0002ac480, 0x114, 0x160aa2a, 0x3)
	/Users/jianghongchao/go/pkg/mod/github.com/xxjwxc/public@v0.0.0-20200404170513-2f5f74aae818/mylog/mylog.go:100 +0x382
github.com/xxjwxc/public/mysqldb.DbLog.Print(0x0, 0x0, 0xc000380a80, 0x3, 0x3)
	/Users/jianghongchao/go/pkg/mod/github.com/xxjwxc/public@v0.0.0-20200404170513-2f5f74aae818/mysqldb/log.go:36 +0x99
github.com/jinzhu/gorm.(*DB).print(0xc0003b40d0, 0xc000380a80, 0x3, 0x3)
	/Users/jianghongchao/go/pkg/mod/github.com/jinzhu/gorm@v1.9.11/main.go:841 +0x52
created by github.com/jinzhu/gorm.(*DB).AddError
	/Users/jianghongchao/go/pkg/mod/github.com/jinzhu/gorm@v1.9.11/main.go:781 +0x2fc

**Comment by hutu1st** [comment]
以下为我的建表语句：

DROP TABLE if exists `ams`.`match`;
CREATE TABLE `ams`.`match`
(
    `id`           int(11) unsigned NOT NULL AUTO_INCREMENT,
    `account_id`   int(11) unsigned NOT NULL,
    `match_id`     varchar(255)     NOT NULL DEFAULT '',
    `symbol`       varchar(255)     NOT NULL DEFAULT '',
    `direction`    varchar(255)     NOT NULL DEFAULT '',
    `exchange`     varchar(255)     NOT NULL DEFAULT '',
    `match_time`   varchar(255)     NOT NULL DEFAULT '',
    `fee_currency` varchar(255)     NOT NULL DEFAULT '',
    `price`        decimal(32, 8)   NOT NULL DEFAULT 0,
    `amount`       decimal(32, 8)   NOT NULL DEFAULT 0,
    `fee`          decimal(32, 8)   NOT NULL DEFAULT 0,
    `update_time`  int(13) unsigned NOT NULL DEFAULT 0,
    `created_time` int(13) unsigned NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE (`match_id`)
) ENGINE = InnoDB;


# 报单表
DROP TABLE if exists `ams`.`order`;
CREATE TABLE `ams`.`order`
(
    `id`           int(11) unsigned NOT NULL AUTO_INCREMENT,
    `account_id`   int(11) unsigned NOT NULL,
    `order_id`     varchar(255)     NOT NULL DEFAULT '',
    `symbol`       varchar(255)     NOT NULL DEFAULT '',
    `direction`    varchar(255)     NOT NULL DEFAULT '',
    `exchange`     varchar(255)     NOT NULL DEFAULT '',
    `match_time`   varchar(255)     NOT NULL DEFAULT '',
    `price`        decimal(32, 8)   NOT NULL DEFAULT 0,
    `amount`       decimal(32, 8)   NOT NULL DEFAULT 0,
    `update_time`  int(13) unsigned NOT NULL DEFAULT 0,
    `created_time` int(13) unsigned NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE (`order_id`)
) ENGINE = InnoDB;

**Comment by xxjwxc** [comment]
ok,roger!

**Comment by xxjwxc** [comment]
the new release bin file will be push asap.

**Comment by xxjwxc** [comment]
version is updated ： 
[v3.0.6](https://github.com/xxjwxc/gormt/releases/tag/v3.0.6)
