### ISSUE TITLE
can not parse cmd flags

### ISSUE THREAD

**Issue by foolishnoob** [xxjwxc/gormt#51]
./gormt -H=127.0.0.1 --port=3306 -d=db_order -p=Jd8fW -u=root -o=models -s=true

Can't read cmd: using （-h, --help) to get more imfo
error info:  Key: 'MysqlDbInfo.Port' Error:Field validation for 'Port' failed on the 'required' tag Key: 'MysqlDbInfo.Port' Error:Field validation for 'Port' failed on the 'required' tag

**Comment by xxjwxc** [comment]
![image](https://user-images.githubusercontent.com/9114492/81199946-e7fb7f80-8ff5-11ea-9af4-405afa5c2d40.png)

Maybe you should download the latest version

**Comment by xxjwxc** [comment]
you get this pb maybe --port=0

![image](https://user-images.githubusercontent.com/9114492/81201231-a1a72000-8ff7-11ea-8752-e42332fa6082.png)

like:
./gormt -H=127.0.0.1 --port=0 -d=db_order -p=Jd8fW -u=root -o=models -s=true

**Comment by foolishnoob** [comment]
thank u very much . 
when i download the binary file from https://github.com/xxjwxc/gormt/releases/download/v3.0.6/gormt_linux.zip , it does not work , and i  solved this problem by download the https://github.com/xxjwxc/gormt/archive/v3.0.6.tar.gz and build ,it is useful now.
