### ISSUE TITLE
Cannot get latest version: module contains a go.mod file, so module path should be github.com/xxjwxc/gormt/v3

### ISSUE THREAD

**Issue by KateGo520** [xxjwxc/gormt#54]
## Background
The `github.com/xxjwxc/gormt` uses [Go modules](https://github.com/golang/go/wiki/Modules) and the current release version is `v3`. And it’s module path is `"github.com/xxjwxc/gormt"`, instead of `"github.com/xxjwxc/gormt/v3"`. It must comply with the specification of "Releasing Modules for v2 or higher" available in the Modules documentation. Quoting the specification:
> A package that has opted in to modules _must_ include the major version in the import path to import any v2+ modules
> To preserve import compatibility, the go command requires that modules with major version v2 or later use a module path with that major version as the final element. For example, version v2.0.0 of _example.com/m_ must instead use module path _example.com/m/v2_.
https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

## Steps to Reproduce
GO111MODULE=on, run `go get` targeting any version >= v2.0.0 of the `xxjwxc/gormt`:
```
$ go get github.com/xxjwxc/gormt@v3.0.6
go: finding github.com/xxjwxc/gormt v3.0.6
go: finding github.com/xxjwxc/gormt v3.0.6
go get github.com/xxjwxc/gormt@v3.0.6: github.com/xxjwxc/gormt@v3.0.6: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v3
```
run `go get github.com/xxjwxc/gormt`, the version will stuck in v1.1.2:
```
$go get github.com/xxjwxc/gormt
go: downloading github.com/xxjwxc/gormt v1.1.2
go: github.com/xxjwxc/gormt upgrade => v1.1.2 
```
SO anyone using Go modules will not be able to easily use any newer version of `xxjwxc/gormt`.

### 1. Kill the go.mod files, rolling back to GOPATH.
This would push them back to not being managed by Go modules (instead of incorrectly using Go modules).
Ensure compatibility for downstream module-aware projects and module-unaware projects projects

### 2. Fix module path to strictly follow SIV rules.
Patch the `go.mod` file to declare the module path as `github.com/xxjwxc/gormt/v3` as [per the specs](https://github.com/golang/go/wiki/Modules#semantic-import-versioning). And adjust all internal imports.
The downstream projects might be negatively affected in their building if they are module-unaware (Go versions older than 1.9.7 and 1.10.3; Or use third-party dependency management tools, such as: Dep, glide,govendor…).

If you don't want to break the above repos. This method can provides better backwards-compatibility.
Release a v2 or higher module through the major subdirectory strategy: Create a new v3 `subdirectory` (github.com/xxjwxc/gormt/v3) and place a new go.mod file in that subdirectory. The `module path` must end with `/v3`. Copy or move the code into the v3 subdirectory. Update `import statements` within the module to also use `/v3` (import "github.com/xxjwxc/gormt/v3/…"). Tag the release with `v3.x.y`.

### 3.  Suggest your downstream module users use hash instead of a version tag.
If the standard rule of go modules conflicts with your development mode. Or not intended to be used as a library and does not make any guarantees about the API. So you can’t comply with the specification of "Releasing Modules for v2 or higher" available in the Modules documentation. 
Regardless, since it's against one of the design choices of Go, it'll be a bit of a hack. Instead of `go get github.com/xxjwxc/gormt@version-tag`, module users need to use this following way to get the `xxjwxc/gormt`:
   (1) Search for the `tag` you want (in browser)
   (2) Get the `commit hash` for the `tag` you want
   (3) Run `go get github.com/xxjwxc/gormt@commit-hash`
   (4) Edit the go.mod file to put a comment about which version you actually used
This will make it difficult for module users to get and upgrade `xxjwxc/gormt`.

**[*]** You can see who will be affected here: [5 module users, e.g., weblazy/orm, psychopurp/Finders-Server, olongfen/note]
https://github.com/search?q=%22github.com%2Fxxjwxc%2Fgormt%22+filename%3Ago.mod&type=Code

## Summary
You can make a choice to fix DM issues by balancing your own development schedules/mode against the affects on the downstream projects.

For this issue, `Solution 2` can maximize your benefits and with minimal impacts to your downstream projects the ecosystem. 

## References
* https://github.com/golang/go/wiki/Modules#semantic-import-versioning
* https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning
* https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

**Comment by xxjwxc** [comment]
tiis is a problem

**Comment by xxjwxc** [comment]
Please Check it out for me

**Comment by KateGo520** [comment]
@xxjwxc   Thank you for your contribution. I see the version has turn to v0.3.8. Now, I can get it. 
Thank you for your reply!
Kate
