### ISSUE TITLE
Gui界面很实用，请问如何退出界面？

### ISSUE THREAD

**Issue by brookbnu** [xxjwxc/gormt#57]
MacBook Pro Cacalina
iTerm2 Build 3.3.9
Gui界面非常实用，尝试了vim各种退出，必须直接关闭命令窗口吗？

**Comment by xxjwxc** [comment]
commond + c就可以退出了。跟其他程序一样的退出当时

**Comment by brookbnu** [comment]
非常感谢

**Comment by xxjwxc** [comment]
- ̗̀(๑ᵔ⌔ᵔ๑)，感谢你的小星星支持😁
