### ISSUE TITLE
生成快捷函数会产生重复重复函数，以及comment分行导致的报错

### ISSUE THREAD

**Issue by Warmriver** [xxjwxc/gormt#60]
![image](https://user-images.githubusercontent.com/19277554/84747797-5450a200-afea-11ea-8c52-21e0b2492aa7.png)
![image](https://user-images.githubusercontent.com/19277554/84747817-5dda0a00-afea-11ea-8a4d-5507ba6bd06b.png)

**Comment by xxjwxc** [comment]
ok,您可以，把数据库表信息发我吗？我微信：xie1xiao1jun

**Comment by xxjwxc** [comment]
问题已修复：
https://github.com/xxjwxc/gormt/commit/19b39a0b41181c37032b1999d1684e16d7e0ee59

**Comment by Warmriver** [comment]
不好意思～ sql没有及时给到。新的修复亲测后ok，以上两个问题不再出现了，赞👍

**Comment by Warmriver** [comment]
@xxjwxc btw，还有个问题不会调，请问mysql的tinyint怎么应设成非bool呢，因为我的tinyint会有0，1，2等值，bool装不下，不知道怎么设置（不清楚是不是bug，先确认下）
![image](https://user-images.githubusercontent.com/19277554/85089544-7843fb80-b215-11ea-8638-1b65b074c84e.png)
