### ISSUE TITLE
请问Mysql tinyint怎么转成非bool呢

### ISSUE THREAD

**Issue by Warmriver** [xxjwxc/gormt#61]
请问mysql的tinyint怎么应设成非bool呢，因为我的tinyint会有0，1，2等值，bool装不下
![image](https://user-images.githubusercontent.com/19277554/85089770-0a4c0400-b216-11ea-8668-6a050d5f7df9.png)

**Comment by xxjwxc** [comment]
![image](https://user-images.githubusercontent.com/9114492/85090025-afff7300-b216-11ea-927b-3a3ac2cc7a6c.png)
tinyint(1)是bool 其他的都是int8

**Comment by xxjwxc** [comment]
https://github.com/xxjwxc/gormt/blob/master/data/view/cnf/def.go

tinyint(1) 转成int8我记得好像是要报错。gorm保存的时候

**Comment by Warmriver** [comment]
保存报错，是指什么呢？我更改了def后，生成成功了（如图），
请问tinyint(1)表示0或1是某种规范吗？（是公司级别还是行业级别呢），如果是公司级别 会不会说明下比较好
![image](https://user-images.githubusercontent.com/19277554/85090597-1769f280-b218-11ea-99db-be47f65119ee.png)
![image](https://user-images.githubusercontent.com/19277554/85090681-4e400880-b218-11ea-8cb9-38d01afd9941.png)

**Comment by xxjwxc** [comment]
你试下保存呢？gorm.Save

**Comment by Warmriver** [comment]
gorm save和gorm gui中保存都没有问题

**Comment by Warmriver** [comment]
![image](https://user-images.githubusercontent.com/19277554/85093071-c4933980-b21d-11ea-88b0-b6f21a472936.png)
Save可以（上面那条我理解错了）

**Comment by Warmriver** [comment]
但是如果字段为null时，转出来会自动转成0，例如图中int64类型，其实是null，查出来是0，所以需要改成*int64，gormt中可以配置字段*type吗？
![image](https://user-images.githubusercontent.com/19277554/85093302-792d5b00-b21e-11ea-8c98-de17521c92c8.png)

**Comment by xxjwxc** [comment]
> 但是如果字段为null时，转出来会自动转成0，例如图中int64类型，其实是null，查出来是0，所以需要改成*int64，gormt中可以配置字段*type吗？
> ![image](https://user-images.githubusercontent.com/19277554/85093302-792d5b00-b21e-11ea-8c98-de17521c92c8.png)

这个是个问题，好像可以通过设置默认值来确定是否是指针类型。我后边看下能不能更新一下。

**Comment by Warmriver** [comment]
感谢付出～ 这个THREAD讨论的问题已经定论，我close了

**Comment by xxjwxc** [comment]
> 但是如果字段为null时，转出来会自动转成0，例如图中int64类型，其实是null，查出来是0，所以需要改成*int64，gormt中可以配置字段*type吗？
> ![image](https://user-images.githubusercontent.com/19277554/85093302-792d5b00-b21e-11ea-8c98-de17521c92c8.png)

“default NULL” 默认值为空，设置成指针类型的功能。已经添加
https://github.com/xxjwxc/gormt/commit/0706dd0747ac5a699f7474140dc1ae0b8eae27da

请检查是否复合你的场景
