### ISSUE TITLE
是否考虑支持sqlite数据库?

### ISSUE THREAD

**Issue by garryforreg** [xxjwxc/gormt#64]

**Comment by xxjwxc** [comment]
https://github.com/xxjwxc/gormt/blob/master/data/view/model/def_ifs.go
按照结构来说是支持的。需要实现：
IModel 接口，

按照目前设计是支持其它数据库的。

**Comment by xxjwxc** [comment]
已经支持sqlite。
https://github.com/xxjwxc/gormt/commit/36b6de2a7b48cc1478ef6af69aa2f4d90a20ea2e
