### ISSUE TITLE
下载时有错误？

### ISSUE THREAD

**Issue by ruixule** [xxjwxc/gormt#65]
![图片](https://user-images.githubusercontent.com/33270841/88470685-048ec000-cf32-11ea-9240-90f1faf5622e.png)

**Comment by ruixule** [comment]
我建议将教程可以详细下吗？go get 后 如何进行下一步操作？

**Comment by xxjwxc** [comment]
可以加一个联系方式吗？我微信号：jnpher
想看看具体错误信息。

**Comment by ruixule** [comment]
> jnpher

好的 谢谢作者

**Comment by xxjwxc** [comment]
已解决
