### ISSUE TITLE
execute fail

### ISSUE THREAD

**Issue by chenyihui555** [xxjwxc/gormt#7]
panic: type (tinyint(2)) not match in any way.

**Comment by chenyihui555** [comment]
执行失败提示类型不支持

**Comment by xxjwxc** [comment]
您需要在：https://github.com/xxjwxc/gormt/blob/master/data/view/gtools/def.go
里面添加 tinyint(2) 这个转换。

请pull requests 让它更完善。谢谢。

**Comment by chenyihui555** [comment]
是在 TypeDicMp 里面加 tinyint(2)的类型吗？

**Comment by xxjwxc** [comment]
好像应该在：TypeMatchMp 中添加一个
`^(tinyint)[(]\d+[)]`:         "int8",

这边实现逻辑是：先精确查找，如果找不到，再模糊匹配。
所以tinyint(n)  (n>1)时应该 走模糊匹配。

**Comment by chenyihui555** [comment]
那就麻烦 大哥更新下源码....

**Comment by chenyihui555** [comment]
或者我提个合并请求？

**Comment by xxjwxc** [comment]
您提交一个吧。我来合并。

**Comment by xxjwxc** [comment]
> 或者我提个合并请求？

代码以及重构。请查看：
https://github.com/xxjwxc/gormt/blob/master/data/view/cnf/def.go
