### ISSUE TITLE
panic: type (float unsigned) not match in any way.maybe need to add on (https://github.com/xxjwxc/gormt/blob/master/data/view/cnf/def.go)

### ISSUE THREAD

**Issue by yijie8** [xxjwxc/gormt#71]
panic: type (float unsigned) not match in any way.maybe need to add on (https://github.com/xxjwxc/gormt/blob/master/data/view/cnf/def.go)

**Comment by xxjwxc** [comment]
需要在： https://github.com/xxjwxc/gormt/blob/master/data/view/cnf/def.go
中添加 `float unsigned` 的映射关系

**Comment by xxjwxc** [comment]
配置已添加
https://github.com/xxjwxc/gormt/commit/285caffe7a2e03aeee203a965a7e2a95fc1e53db
