### ISSUE TITLE
gorm.Model id主键 无法导出到 json

### ISSUE THREAD

**Issue by json7** [xxjwxc/gormt#74]
gorm.Model 里的 id主键 没有json tag. 把结构体转成结构体的时候 json里没有id这个key

**Comment by xxjwxc** [comment]
is_web_tag_pk_hidden : true 可以试下

**Comment by json7** [comment]
已经加了,就是不行

**Comment by json7** [comment]
如果主键名称不叫id, 比如 user_id 这样都是可以导出来的. 如果是id,则就成了gorm.Model

**Comment by xxjwxc** [comment]
gorm.Model 是gorm的内建结构。没办法追加json tag.

**Comment by json7** [comment]
可以决定加不加gorm.Model吧.算了,我 手动替换吧

**Comment by xxjwxc** [comment]
你可以fork一下，改一下。
