### ISSUE TITLE
sql: not null default 'xxx' 默认值怎么输入到gorm struct

### ISSUE THREAD

**Issue by zibber2015** [xxjwxc/gormt#75]

**Comment by xxjwxc** [comment]
目前还不支持，后边会想办法实现

**Comment by xxjwxc** [comment]
已经支持默认值：default

https://github.com/xxjwxc/gormt/commit/aa434356e022587c3f04cf1b1a7929eca1eb2382

**Comment by zibber2015** [comment]
是读取comment里的default值 不是sql的default值吗

**Comment by xxjwxc** [comment]
嗯，是的，sql default里面的默认值，是否有必要支持。目前解决办法是COMMENT里面加入注解来做。

 COMMENT='[@gormt default:'admin']用户账号' 

类似这种

**Comment by zibber2015** [comment]
好的 谢谢👍

**Comment by xxjwxc** [comment]
问题已解决
