### ISSUE TITLE
panic: type (double unsigned) not match in any way

### ISSUE THREAD

**Issue by quhaowk** [xxjwxc/gormt#82]
panic: type (double unsigned) not match in any way.maybe need to add on (https://github.com/xxjwxc/gormt/blob/master/data/view/cnf/def.go)

goroutine 1 [running]:
github.com/xxjwxc/gormt/data/view/model.getTypeName(0xc000419580, 0xf, 0x1390c00, 0x1, 0x1390cc3)
        /Users/xxj/work/workspace/github/xxjwxc/gormt/data/view/model/common.go:71 +0x57f
github.com/xxjwxc/gormt/data/view/model.(*_Model).genTableElement(0xc00049fc20, 0xc000434800, 0xf, 0x11, 0x5, 0x5, 0x0)
        /Users/xxj/work/workspace/github/xxjwxc/gormt/data/view/model/model.go:84 +0xea5
github.com/xxjwxc/gormt/data/view/model.(*_Model).GetPackage(0xc00049fc20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/xxj/work/workspace/github/xxjwxc/gormt/data/view/model/model.go:55 +0x271
github.com/xxjwxc/gormt/data/view/model.(*_Model).generate(0xc00049fc20, 0xc0001a7988, 0x8)
        /Users/xxj/work/workspace/github/xxjwxc/gormt/data/view/model/model.go:67 +0x45
github.com/xxjwxc/gormt/data/view/model.Generate(0xc0001a7998, 0x8, 0xc0001a760a, 0x5, 0xc000196000, 0x8c, 0x11c, 0x11c, 0xc0003607b0, 0x1391d30, ...)
        /Users/xxj/work/workspace/github/xxjwxc/gormt/data/view/model/model.go:31 +0xaa
github.com/xxjwxc/gormt/data/view/gtools.showCmd()
        /Users/xxj/work/workspace/github/xxjwxc/gormt/data/view/gtools/gtools.go:51 +0x13f
github.com/xxjwxc/gormt/data/view/gtools.Execute()
        /Users/xxj/work/workspace/github/xxjwxc/gormt/data/view/gtools/gtools.go:24 +0x3e
github.com/xxjwxc/gormt/data/cmd.glob..func1(0x1802ee0, 0x185f540, 0x0, 0x0)
        /Users/xxj/work/workspace/github/xxjwxc/gormt/data/cmd/cmd.go:29 +0x27
github.com/spf13/cobra.(*Command).execute(0x1802ee0, 0xc0000541a0, 0x0, 0x0, 0x1802ee0, 0xc0000541a0)
        /Users/xxj/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x1802ee0, 0x0, 0x0, 0x0)
        /Users/xxj/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/xxj/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/xxjwxc/gormt/data/cmd.Execute()
        /Users/xxj/work/workspace/github/xxjwxc/gormt/data/cmd/cmd.go:37 +0x34
main.main()
        /Users/xxj/work/workspace/github/xxjwxc/gormt/main.go:6 +0x27

在win10下运行报错, go version go1.15.2 windows/amd64

**Comment by quhaowk** [comment]
![Uploading image.png…]()

**Comment by quhaowk** [comment]
base:
    is_dev : false
out_dir : ./model  # 输出目录
url_tag : json # web url tag(json,db(https://github.com/google/go-querystring))
language : English # 语言(English,中 文)
db_tag : gorm # 数据库标签(gorm,db)
singular_table : true  # 单表模式:true:禁用表名复数,false:采用表名复数 参考:gorm.SingularTable
simple : false # 简单输出(默认gorm标签不输出)
is_out_sql : false # 是否输出 sql 原信息
is_out_func : true # 是否输出 快捷函数
is_web_tag : true # 是否打web标记(json标记前提条件)
is_web_tag_pk_hidden: true # web标记是否隐藏主键
is_foreign_key : true # 是否导出外键关联
is_gui : false # 是否ui模式显示
is_table_name : false # 是否直接生成表名函数
is_null_to_point : false # 数据库默认 'DEFAULT NULL' 时设置结构为指针类型
db_info:
    host : 127.0.0.1 # type=1的时候，host为yml文件全路径
    port : 3306
    username : root
    password : "test"
    database : "test"
    type: 0 # 数据库类型:0:mysql , 1:sqlite , 2:mssql

**Comment by xxjwxc** [comment]
看提示，panic,类型需要添加进去，欢迎merge到master

**Comment by xxjwxc** [comment]
type (double unsigned) not match in any way.maybe need to add on (https://github.com/xxjwxc/gormt/blob/master/data/view/cnf/def.go)

**Comment by xxjwxc** [comment]
已经合并：https://github.com/xxjwxc/gormt/commit/cdb5710723419df01b13f8e9fcbea5c1e8be7477
