### ISSUE TITLE
新版本 gorm WithConditions字段已经去除

### ISSUE THREAD

**Issue by heyingjie** [xxjwxc/gormt#91]
新版本 gorm WithConditions字段已经去除，在生成的代码中需要去掉该字段

**Comment by xxjwxc** [comment]
ok,方便提一個mr，我来合并
thx

**Comment by xxjwxc** [comment]
https://github.com/xxjwxc/gormt/commit/cfb3d5edde047290239f9d05f8790ab73675d20b
已经移除。
