### ISSUE TITLE
status字段生成model的时候变为Statu

### ISSUE THREAD

**Issue by Pissssofshit** [xxjwxc/gormt#93]
这是我的config.yml配置
```
base:
    is_dev: false
db_info:
    host: 127.0.0.1
    port: 3306
    username: root
    password: 123456
    database: competitorAnalysis
    type: 0
out_dir: ./internal/model/
url_tag: json
language: english
db_tag: gorm
is_web_tag_pk_hidden: false
is_foreign_key: true
is_out_sql: false
is_out_func: false
is_gui: false
is_table_name: false
is_null_to_point: false
singular_table : false 
simple : true 
is_web_tag : false
```
这是我的sql,每张表里的status字段都是生成为
```
Statu int 
```
所以我只放一张表的sql上来，
```
CREATE TABLE `version` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `status` int NOT NULL DEFAULT '1' COMMENT '状态',
  `gmt_create` bigint NOT NULL COMMENT '创建时间',
  `gmt_modified` bigint NOT NULL COMMENT '更新时间',
  `online_time` bigint NOT NULL COMMENT '上线时间',
  `market_id` bigint NOT NULL COMMENT 'market id',
  `version` varchar(255) NOT NULL COMMENT '应用版本',
  `bundle_id` varchar(255) NOT NULL COMMENT '包名',
  `app_name` varchar(255) NOT NULL COMMENT '应用名字',
  `app_icon` varchar(255) DEFAULT NULL COMMENT '应用图标',
  `developer` varchar(255) NOT NULL COMMENT '开发者',
  `package_size` bigint NOT NULL COMMENT '包大小',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='版本';
```
生成的字段
![截屏2020-12-03 上午10 44 58](https://user-images.githubusercontent.com/28259468/100956966-99df3800-3554-11eb-8695-697976af94a9.png)

**Comment by xxjwxc** [comment]
收到

**Comment by Pissssofshit** [comment]
不光是字段，表名中的s也消失了，sql就不放了
![截屏2020-12-03 上午10 47 33](https://user-images.githubusercontent.com/28259468/100957175-f4789400-3554-11eb-8724-b3029ab74557.png)

**Comment by xxjwxc** [comment]
config.yml 有一个配置：singular_table

请尝试将其配置成false

**Comment by Pissssofshit** [comment]
> config.yml 有一个配置：singular_table
> 
> 请尝试将其配置成false

你好，配置文件(位于gormt的同级目录下）中的配置
singular_table是false,
使用方式是在项目下直接运行gormt
我把整个数据库导出来添加到附件了，
也许对调试有帮助
[competitorAnalysis.sql.zip](https://github.com/xxjwxc/gormt/files/5634409/competitorAnalysis.sql.zip)

**Comment by Pissssofshit** [comment]
> config.yml 有一个配置：singular_table
> 
> 请尝试将其配置成false

singular_table配置成true之后可以了

**Comment by xxjwxc** [comment]
项目下直接运行gormt ,需要找到这个运行的gormt 的存放目录，直接改掉当前目录的config.yml 配置即可

**Comment by Pissssofshit** [comment]
> 项目下直接运行gormt ,需要找到这个运行的gormt 的存放目录，直接改掉当前目录的config.yml 配置即可

了解了

**Comment by xxjwxc** [comment]
我刚审视了一下，发现v2版本不需要表名复数了。所以我决定去掉这个选项。后继请留意更新

**Comment by xxjwxc** [comment]
已经删除表名复数模式：
https://github.com/xxjwxc/gormt/commit/3516c2b4a5357f5ec82fa6247333ad8b63e7f27a
