### ISSUE TITLE
有计划生成struct的时候顺便把 字段字符串也生成出来吗

### ISSUE THREAD

**Issue by siyue8899** [xxjwxc/gormt#94]
```go
type User struct{
  ID int
 Name string
}

Columns = struct {
	ID              string
        Name         string       
	}{
	ID:  "id",                  
        Name: "name",           
	}
```

类似这样的，然后使用gorm 的 Select(Columns.Name)   ,就可以了不用写死硬编码字符串容易出错

**Comment by xxjwxc** [comment]
好建议，请留意更新

**Comment by xxjwxc** [comment]
已经添加：
https://github.com/xxjwxc/gormt/commit/bceb63b951b8d76c57990e876ad77a4225cb985f
请配置config.yml   
is_table_name : true

**Comment by siyue8899** [comment]
> 已经添加：
> [bceb63b](https://github.com/xxjwxc/gormt/commit/bceb63b951b8d76c57990e876ad77a4225cb985f)
> 请配置config.yml
> is_table_name : true

神速啊感谢哈哈

**Comment by lifegit** [comment]
改种方式会存在安全隐患呀！ #159
