### ISSUE TITLE
已经配置yml文件， 但是一直报错  没有权限

### ISSUE THREAD

**Issue by day112** [xxjwxc/gormt#95]
[error] failed to initialize database, got error Error 1045: Access denied for user 'root'@'localhost' (using password: YES)
2020/12/08 18:26:55 Got error when connect database:root:root@tcp(127.0.0.1:3306)/test?charset=utf8&parseTime=True&loc=Local&interpolateParams=True: Error 1045: Access denied for user 'root'@'localhost' (using password: YES)

**Comment by xxjwxc** [comment]
config.yam要跟执行的程序放同一级目录。需要帮忙看下的话，可以加我微信号
