### ISSUE TITLE
字段类型识别错误

### ISSUE THREAD

**Issue by zhangxinwu** [xxjwxc/gormt#99]
字段类型为 `int unsigned`，导出model的字段类型应为uint32；但偶现为int

https://github.com/xxjwxc/gormt/blob/3516c2b4a5357f5ec82fa6247333ad8b63e7f27a/data/view/model/common.go#L65
`TypeMysqlMatchMp` hashMap无序，无法保证unsigned优先判断

建议改成数组，unsigned放在signed前判断

**Comment by xxjwxc** [comment]
收到

**Comment by xxjwxc** [comment]
fix
https://github.com/xxjwxc/gormt/commit/a60ccdc6957ef90b4e109ec63eb0fcc8dbbe79ff
